package backend.score.file

import java.util.regex.Pattern

import backend.recon.{Album, Artist, Track}
import backend.score.{IndividualScorer, OptionalModelScore}
import backend.score.file.ScoreParser.OrgPrefix
import backend.score.storage.{AlbumScoreStorage, ArtistScoreStorage, TrackScoreStorage}
import com.google.inject.Inject

import scala.concurrent.{ExecutionContext, Future}
import scala.util.Try

import cats.implicits.toFoldableOps
import common.rich.func.TuplePLenses.__1
import common.rich.func.kats.ToMoreFunctorOps.toMoreFunctorOps

import common.Trither
import common.rich.RichTuple.richTuple2
import common.rich.primitives.RichString._

/** Parses the .org file generated by [[MassScorer]]. */
private class ScoreParser @Inject() (
    artistScoreStorage: ArtistScoreStorage,
    albumScoreStorage: AlbumScoreStorage,
    trackScoreStorage: TrackScoreStorage,
    scorer: IndividualScorer,
    ec: ExecutionContext,
) {
  private implicit val iec: ExecutionContext = ec

  def parseLines(lines: Seq[String]): Future[Unit] = {
    val changes = lines.flatMap(parse)
    if (changes.isEmpty) {
      scribe.info("No score changes")
      return Future.successful(())
    }

    val (artists, albums, tracks) =
      Trither.partition(changes.view.map(_.reduce(_.tritherStrengthenLeft(_))))
    // FIXME multiple overwrite void silently fails on foreign key error
    Vector(
      artistScoreStorage.updateAll(artists),
      albumScoreStorage.updateAll(albums),
      trackScoreStorage.updateAll(tracks),
    ).sequence_
  }

  // Returns None if line isn't a score line, or if the score hasn't changed.
  private def parse(line: String): Option[(Trither[Artist, Album, Track], OptionalModelScore)] = {
    val withoutPrefix = line.removeAll(OrgPrefix)
    // TODO use the parser here as well, using either or something.
    val $ : Try[(Trither[Artist, Album, Track], OptionalModelScore)] =
      if (withoutPrefix.startsWith("ARTIST"))
        ArtistScoreParser(line).map(__1.modify(Trither.TriLeft.apply))
      else if (withoutPrefix.startsWith("ALBUM"))
        AlbumScoreParser(line).map(__1.modify(Trither.TriMid.apply))
      else if (withoutPrefix.startsWith("SONG"))
        TrackScoreParser(line).map(__1.modify(Trither.TriRight.apply))
      else
        return None
    $.filter(e =>
      e._1.fold(
        scorer.explicitScore,
        scorer.explicitScore,
        scorer.explicitScore,
      ) != e._2,
    ).toOption.listen(e => scribe.info(s"Storing <$e>"))
  }
}

private object ScoreParser {
  private val OrgPrefix = Pattern.compile("""^\** """)
}
