package backend.scorer.utils

import javax.inject.Inject

import backend.recon.{Album, Artist, Track}
import backend.scorer.{CachedModelScorer, ModelScore, OptionalModelScore}
import backend.scorer.storage.ArtistScoreStorage

import scala.collection.mutable.ArrayBuffer
import scala.concurrent.{ExecutionContext, Future}
import scala.util.Try

import common.rich.func.BetterFutureInstances._
import common.rich.func.MoreTraverseInstances._
import common.rich.func.ToMoreFunctorOps.toMoreFunctorOps
import common.rich.func.TuplePLenses
import scalaz.Scalaz.{optionInstance, ToFunctorOps, ToTraverseOpsUnapply}

import common.Trither
import common.io.FileRef
import common.rich.primitives.RichBoolean.richBoolean
import common.rich.primitives.RichString._

/** Parses the .org file generated by [[AlbumScoreToOrg]]. */
private class ScoreParser @Inject() (
    artistScoreStorage: ArtistScoreStorage,
    cachedModelScorer: CachedModelScorer,
    ec: ExecutionContext,
) {
  private implicit val iec: ExecutionContext = ec

  private def parse(line: String): Option[(Trither[Artist, Album, Track], OptionalModelScore)] = {
    val withoutPrefix = line.removeAll("^\\** ")
    // TODO use the parser here as well, using either or something.
    if (
      (withoutPrefix.startsWith("ARTIST") || withoutPrefix.startsWith("ALBUM") || withoutPrefix
        .startsWith("SONG")).isFalse
    )
      return None

    val $ : Try[(Trither[Artist, Album, Track], OptionalModelScore)] =
      if (withoutPrefix.startsWith("ARTIST"))
        ArtistScoreParser(line).map(TuplePLenses.tuple2First.modify(Trither.TriLeft.apply))
      else if (withoutPrefix.startsWith("ALBUM"))
        AlbumScoreParser(line).map(TuplePLenses.tuple2First.modify(Trither.TriMid.apply))
      else {
        assert(withoutPrefix.startsWith("SONG"))
        TrackScoreParser(line).map(TuplePLenses.tuple2First.modify(Trither.TriRight.apply))
      }
    $.filter(e =>
      e._1.fold(
        cachedModelScorer.explicitScore,
        cachedModelScorer.explicitScore,
        cachedModelScorer.explicitScore,
      ) != e._2,
    ).toOption.listen(e => scribe.info(s"Storing <$e>"))
  }
  private def store(scores: Seq[(Trither[Artist, Album, Track], ModelScore)]): Future[Unit] = {
    // Sorry :/ TODO replace with separate for trifolds
    val artists = ArrayBuffer[(Artist, ModelScore)]()
    val albums = ArrayBuffer[(Album, ModelScore)]()
    val tracks = ArrayBuffer[(Track, ModelScore)]()
    for ((trither, score) <- scores)
      trither match {
        case Trither.TriLeft(a) => artists += ((a, score))
        case Trither.TriMid(b) => albums += ((b, score))
        case Trither.TriRight(c) => tracks += ((c, score))
      }
    assert(albums.isEmpty)
    assert(tracks.isEmpty)
    // FIXME multiple overwrite void silently fails on foreign key error
    artists.traverse(Function.tupled(artistScoreStorage.replace)).run.void
  }
  def parseFile(file: FileRef): Future[Unit] = parseLines(file.lines)
  def parseLines(lines: Seq[String]): Future[Unit] =
    store(lines.flatMap(parse).flatMap(e => e._2.toModelScore.map(e._1 -> _)))
}
